import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { ExpediaWidgetManager } from "@/contexts/ExpediaWidgetManager";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          id="expedia-widgets"
          src="https://creator.expediagroup.com/products/widgets/assets/eg-widgets.js"
          strategy="afterInteractive"
          className="eg-widgets-script"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ExpediaWidgetManager>{children}</ExpediaWidgetManager>
      </body>
    </html>
  );
}
